openapi: 3.0.3
info:
  version: 1.0.0
  title: Water Tracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of water tracker
tags:
  - name: Water
    description: Water usage data operations.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
    description: Development server
paths:
  /auth/register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /auth/update-user:
    post:
      $ref: ../swagger/path/auth/update-user.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/path/auth/get-oauth-url.yaml
  /auth/google-login:
    post:
      $ref: ../swagger/path/auth/google-login.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/path/auth/sendResetEmail.yaml
  /auth/reset-password:
    get:
      $ref: ../swagger/path/auth/reset-password.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/path/auth/resetPwd.yaml
  /auth/current:
    get:
      $ref: ../swagger/path/auth/current.yaml
  /auth/count:
    get:
      $ref: ../swagger/path/auth/count.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
